### ISSUE TITLE
Js-Controller 3.2.x has no existing object

### ISSUE THREAD

**Issue by crunchip77** [iobroker-community-adapters/ioBroker.yeelight-2#81]
folgende Meldung seit Js-Controller upgrade, Adapter version 1.0.3, es handelt sich um eine yeelight meteorite
`

yeelight-2.0 | 2021-01-16 17:45:01.237 | warn | (15186) State "yeelight-2.0.Esstisch.control.bright" has no existing object, this might lead to an error in future versions
-- | -- | -- | --

`

**Comment by Robox** [comment]
Bei mir startet der Adapter auch nicht mit Js-Controller 3.2.x 
Wen ich denn Fehler richtig deute, fehlt eine gültige EXCEPTION.
`

host.ubuntu | 2021-01-21 16:06:10.662 | warn | Do not restart adapter system.adapter.yeelight-2.0 because restart loop detected
-- | -- | -- | --
host.ubuntu | 2021-01-21 16:06:10.662 | info | Restart adapter system.adapter.yeelight-2.0 because enabled
host.ubuntu | 2021-01-21 16:06:10.662 | error | instance system.adapter.yeelight-2.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
yeelight-2.0 | 2021-01-21 16:06:10.086 | warn | (21114) Terminated (UNCAUGHT_EXCEPTION): Without reason
yeelight-2.0 | 2021-01-21 16:06:10.086 | info | (21114) terminating
yeelight-2.0 | 2021-01-21 16:06:10.085 | info | (21114) cleaned everything up...
yeelight-2.0 | 2021-01-21 16:06:10.070 | error | (21114) Cannot read property 'val' of null
yeelight-2.0 | 2021-01-21 16:06:10.070 | error | (21114) TypeError: Cannot read property 'val' of null     at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.yeelight-2/main.js:284:62)     at processImmediate (internal/timers.js:463:21)
yeelight-2.0 | 2021-01-21 16:06:10.069 | error | (21114) uncaught exception: Cannot read property 'val' of null

`

**Comment by entavio** [comment]
Das habe ich auch.... also sowohl "xxxxx.control.bright" has no existing object, this might lead to an error in future versions"
habe ich des häufigeren im Log stehen bzw. der ganze Adapter Crashed sobald man ein Licht schaltet.

**Comment by tugsi** [comment]
Bei mir startet er und läuft, aber er meckert nicht bright an sondern:
State "yeelight-2.0.xxxx.info.connect" has no existing object, this might lead to an error in future versions

**Comment by Ash2k80** [comment]
Kann ich leider bestätigen, hier mein Log-Auszug:

2021-03-24 19:48:34.183 - warn: yeelight-2.0 (24563) State "yeelight-2.0.ceiling3-0x0000000007d1f96e.control.bright" has no existing object, this might lead to an error in future versions

**Comment by crunchip77** [comment]
Nach dem ich meine Lampe neu installiert hatte, kam keine Meldung bezüglich "has no existing object"
